version: "3.7"
services:
  youtube-dl:
    image: "nbr23/youtube-dl-server"
    ports: 
      - 9004:8080
    volumes:
      - ${USERDIR}/vidoes:/youtube-dl
    restart: always
    # https://github.com/nbr23/youtube-dl-server
    # https://hub.docker.com/r/nbr23/youtube-dl-server
