version: '3.7'

# Services
services:

  # Nginx Service
  nginx:
    image: nginx:alpine
    hostname: nginx
    container_name: nginx
    restart: always
    ports:
      - 9001:80 # host port:container port
    volumes:
      - ${USERDIR}/config/nginx/www:/var/www/html:ro
      - ${USERDIR}/config/nginx/conf.d:/etc/nginx/conf.d:ro
      - ${USERDIR}/config/phpmyadmin/config:/usr/src/phpmyadmin
    depends_on:
      - php
      - phpmyadmin
    # https://hub.docker.com/_/nginx
    # https://github.com/nginxinc/docker-nginx/

  # PHP Service
  php:
    build: ${USERDIR}/config/php
    hostname: php
    container_name: php
    restart: always
    working_dir: /var/www/php
    volumes:
      - ${USERDIR}/config/nginx/www:/var/www/html
    depends_on:
      - mariadb
    # https://hub.docker.com/_/php
    # https://github.com/docker-library/php

  # MySQL Service
  mariadb:
    image: mariadb:latest
    hostname: mariadb
    container_name: mariadb
    restart: always
    volumes:
      - ${USERDIR}/config/db/my.cnf:/etc/mysql/conf.d/my.cnf:ro
      - ${USERDIR}/config/db/config:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE="demo"
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    # https://hub.docker.com/_/mariadb
    # https://github.com/docker-library/mariadb

  # PhpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    hostname: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 9002:80
    volumes:
      - ${USERDIR}/config/phpmyadmin/config:/usr/src/phpmyadmin
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    depends_on:
      - mariadb
    # https://hub.docker.com/_/phpmyadmin
    # https://github.com/phpmyadmin/docker
