version: '3.7'
services:
  nginx:
    image: nginx:alpine
    hostname: nginx
    container_name: nginx
    restart: always
    ports:
      - 9001:80 # host port:container port
    volumes:
      - ${USERDIR}/nginx/www:/var/www/html:ro
      - ${USERDIR}/nginx/conf.d:/etc/nginx/conf.d:ro
      - ${USERDIR}/phpmyadmin/config:/usr/src/phpmyadmin
    depends_on:
      - php
      - phpmyadmin
  php:
    build: ${USERDIR}/php
    hostname: php
    container_name: php
    restart: always
    working_dir: /var/www/html
    volumes:
      - ${USERDIR}/nginx/www:/var/www/html
    depends_on:
      - mariadb
  mariadb:
    image: mariadb:latest
    hostname: mariadb
    container_name: mariadb
    restart: always
    volumes:
      - ${USERDIR}/db/my.cnf:/etc/mysql/conf.d/my.cnf:ro
      - ${USERDIR}/db/config:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=demo
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    hostname: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 9002:80
    volumes:
      - ${USERDIR}/phpmyadmin/config:/usr/src/phpmyadmin
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    depends_on:
      - mariadb
  sass:
    image: sass
    hostname: sass
    container_name: sass
    restart: always
    volumes:
       - ${USERDIR}/nginx/www/css:/css
